version: "3.8"
services:
  web:
    build:
      dockerfile: dockerfile/node
      context: ./
      target: dev
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    stdin_open: true
    ports:
      - "80:3000"
    env_file:
      - ./.env
volumes:
  node_modules:
    driver: local
